"use client";

import { useCallback, useEffect, useState } from "react";

import { ImpedanceSpectrumChart, ColePlaneChart } from "@/components/bioimpedance/bioimpedance-charts";
import { MeasurementTable } from "@/components/bioimpedance/measurement-table";
import { ModelInspector } from "@/components/bioimpedance/model-inspector";
import { acquireBilateralSweep, fetchBioimpedanceConfig } from "@/lib/api/bioimpedance";
import type {
  BilateralBioimpedanceSweep,
  BioimpedanceTwinConfiguration,
} from "@/lib/types/bioimpedance";


function formatTimestamp(timestamp: string) {
  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "UTC",
  }).format(new Date(timestamp));
}


export function BioimpedanceTwinPanel({ backendConnected }: { backendConnected: boolean }) {
  const [config, setConfig] = useState<BioimpedanceTwinConfiguration | null>(null);
  const [sweep, setSweep] = useState<BilateralBioimpedanceSweep | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadConfig = useCallback(async (signal?: AbortSignal) => {
    try {
      const response = await fetchBioimpedanceConfig(signal);
      setConfig(response);
      setError(null);
    } catch (requestError) {
      if (requestError instanceof DOMException && requestError.name === "AbortError") return;
      setError("Bioimpedance Digital Twin is unavailable. Acquisition remains disabled.");
    }
  }, []);

  useEffect(() => {
    if (!backendConnected) return;
    const controller = new AbortController();
    const request = window.setTimeout(() => void loadConfig(controller.signal), 0);
    return () => {
      controller.abort();
      window.clearTimeout(request);
    };
  }, [backendConnected, loadConfig]);

  const acquire = async () => {
    setBusy(true);
    setError(null);
    try {
      setSweep(await acquireBilateralSweep());
    } catch (requestError) {
      setError(requestError instanceof Error ? requestError.message : "Bilateral acquisition failed.");
    } finally {
      setBusy(false);
    }
  };

  const enabled = backendConnected && config !== null && !busy;

  return (
    <section className="mt-6 overflow-hidden rounded-3xl border border-[rgba(107,184,230,.18)] bg-[rgba(7,24,28,.82)] shadow-[0_28px_100px_rgba(0,0,0,.18)] backdrop-blur-xl">
      <div className="flex flex-col gap-4 border-b border-[var(--line)] px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-7">
        <div>
          <p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-[#8ed3f3]">Bilateral bioimpedance digital twin</p>
          <h2 className="mt-2 text-xl font-medium tracking-[-0.02em] text-white">Engineering acquisition</h2>
          <p className="mt-1 text-xs text-[var(--muted)]">Synthetic bilateral multi-frequency impedance generated by the Aequor digital twin.</p>
        </div>
        <button type="button" disabled={!enabled} onClick={() => void acquire()} className="rounded-lg border border-[rgba(93,228,207,.25)] bg-[rgba(93,228,207,.08)] px-4 py-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-[var(--aqua)] transition-colors hover:bg-[rgba(93,228,207,.15)] disabled:cursor-not-allowed disabled:border-white/[.06] disabled:bg-white/[.02] disabled:text-[#526361]">
          {busy ? "Acquiring…" : "Acquire bilateral sweep"}
        </button>
      </div>

      <div className="flex flex-wrap gap-2 border-b border-[var(--line)] px-5 py-3 sm:px-7">
        <span className="rounded-full border border-[rgba(107,184,230,.24)] bg-[rgba(107,184,230,.08)] px-3 py-1 text-[9px] font-semibold tracking-[0.14em] text-[#8ed3f3]">SIMULATED</span>
        <span className="rounded-full border border-[rgba(233,185,110,.24)] bg-[rgba(233,185,110,.08)] px-3 py-1 text-[9px] font-semibold tracking-[0.14em] text-[var(--amber)]">RAW / NOT YET QUALITY-GATED</span>
        <span className="px-2 py-1 text-[10px] font-medium tracking-[0.1em] text-[var(--muted)]">SOURCE: DIGITAL TWIN</span>
      </div>

      {!sweep ? (
        <div className="m-5 rounded-2xl border border-dashed border-white/10 p-7 text-sm leading-6 text-[var(--muted)] sm:m-7">
          {backendConnected ? "Acquire a synchronized bilateral sweep to inspect the synthetic complex impedance spectrum." : "Backend disconnected. No sweep is fabricated while the authoritative acquisition service is unavailable."}
        </div>
      ) : (
        <div className="p-5 sm:p-7">
          <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
            <Metadata label="Sweep" value={`#${sweep.sweep_index}`} />
            <Metadata label="Simulation time" value={`${formatTimestamp(sweep.simulated_time)} UTC`} />
            <Metadata label="Provenance" value={sweep.provenance} />
            <Metadata label="Source" value={sweep.source.replaceAll("_", " ")} />
            <Metadata label="Model revision" value={sweep.model_revision} />
          </div>
          <div className="grid gap-7 xl:grid-cols-2">
            <div><p className="mb-4 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#c4d9d5]">Magnitude spectrum</p><ImpedanceSpectrumChart left={sweep.left.points} right={sweep.right.points} /></div>
            <div><p className="mb-4 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#c4d9d5]">Cole plane</p><ColePlaneChart left={sweep.left.points} right={sweep.right.points} /></div>
          </div>
          <div className="mt-7 border-t border-[var(--line)] pt-6">
            <p className="mb-4 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#c4d9d5]">Raw engineering readings</p>
            <MeasurementTable sweep={sweep} />
          </div>
        </div>
      )}

      {config && <div className="border-t border-[var(--line)] p-5 sm:p-7"><ModelInspector config={config} /><p className="mt-4 text-xs leading-5 text-[var(--muted)]">Synthetic instrumentation noise is for digital-twin behavior and is not derived from characterization of the final AD5940 wearable.</p></div>}
      {error && <p role="alert" className="mx-5 mb-5 rounded-xl border border-[rgba(255,143,136,.18)] bg-[rgba(255,143,136,.06)] px-4 py-3 text-xs leading-5 text-[var(--red)] sm:mx-7 sm:mb-7">{error}</p>}
    </section>
  );
}


function Metadata({ label, value }: { label: string; value: string }) {
  return <div className="rounded-xl border border-[var(--line)] bg-white/[.018] p-3"><p className="text-[9px] uppercase tracking-[0.16em] text-[var(--muted)]">{label}</p><p className="mt-2 truncate text-xs font-medium text-[#d7eae7]" title={value}>{value}</p></div>;
}

