"use client";
import { useCallback,useEffect,useState } from "react";
import { TopNav } from "./engineering-console";

const api=process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:8000";
type Definition={challenge_id:string;title:string;question:string;naive_failure_mode:string;expected_invariant:string};
type Result={challenge_id:string;title:string;run_time:string;simulated_start:string;simulated_end:string;status:"PASS"|"FAIL"|"INCONCLUSIVE";observed_evidence:{observations:Record<string,unknown>;invariant_checks:Record<string,boolean|null>};expected_invariant:string;explanation:string;runtime_cycle_ids:string[]};
type Suite={definitions:Definition[];latest_results:Result[];history_count:number};
export function AdversarialChallenge(){
 const [suite,setSuite]=useState<Suite|null>(null),[running,setRunning]=useState<string|null>(null),[expanded,setExpanded]=useState<string|null>(null),[error,setError]=useState(false);
 const load=useCallback(async()=>{try{const response=await fetch(`${api}/api/v1/challenges/status`);if(!response.ok)throw new Error();setSuite(await response.json());setError(false)}catch{setError(true)}},[]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const run=async(id:string)=>{setRunning(id);try{await fetch(`${api}/api/v1/challenges/${id}/run`,{method:"POST"});await load();setExpanded(id)}finally{setRunning(null)}};
 const runAll=async()=>{setRunning("all");try{await fetch(`${api}/api/v1/challenges/run-all`,{method:"POST"});await load()}finally{setRunning(null)}};
 if(error)return <main className="min-h-screen bg-[#080f12] p-8 text-white"><b className="text-[#e0aa77]">BACKEND UNAVAILABLE</b><p className="mt-3 text-sm">Challenge results are hidden until a fresh response is available.</p></main>;
 if(!suite)return <main className="min-h-screen bg-[#080f12] p-8 text-white">Preparing adversarial challenge suite…</main>;
 const latest=new Map(suite.latest_results.map(x=>[x.challenge_id,x]));const passed=suite.latest_results.filter(x=>x.status==="PASS").length;
 return <main className="min-h-screen bg-[#080f12] text-[#e9f0ee]"><TopNav active="Try to Fool Aequor"/><div className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8">
  <header className="relative overflow-hidden rounded-[2rem] border border-[#66c3ad]/20 bg-[#10211f] p-7 sm:p-10"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-[#d17f67]/10 blur-3xl"/><p className="relative text-[11px] font-bold tracking-[.24em] text-[#e39a80]">ADVERSARIAL ENGINEERING TESTS OF THE SURVEILLANCE PIPELINE</p><h1 className="relative mt-3 text-4xl font-light sm:text-6xl">TRY TO FOOL AEQUOR</h1><p className="relative mt-5 max-w-3xl text-sm leading-7 text-[#9dafaa]">These tests deliberately stress the prototype with conditions that could mislead a naive monitoring system. Every verdict is calculated from the actual existing pipeline response.</p><div className="relative mt-7 flex flex-col gap-4 sm:flex-row sm:items-center"><button disabled={running!==null} onClick={()=>void runAll()} className="rounded-full bg-[#e09275] px-6 py-3 text-xs font-bold tracking-wider text-[#1b100d] disabled:opacity-50">{running==="all"?"RUNNING ISOLATED TESTS…":"RUN FULL ADVERSARIAL SUITE"}</button><p className="text-xs text-[#82958f]">Each test resets before and after execution. Model artifacts are never modified.</p></div></header>
  <section className="mt-5 grid gap-3 sm:grid-cols-3"><Summary label="Engineering checks run" value={String(suite.latest_results.length)}/><Summary label="Passed" value={String(passed)}/><Summary label="Current-process history" value={String(suite.history_count)}/></section>
  {suite.latest_results.length>0&&<div className="mt-5 rounded-2xl border border-white/10 bg-white/[.03] p-4 text-center text-sm"><b>{passed} / {suite.latest_results.length}</b> engineering robustness checks passed. This is not accuracy, sensitivity, specificity, or clinical performance.</div>}
  <section className="mt-5 grid gap-5 lg:grid-cols-2">{suite.definitions.map((definition,index)=>{const result=latest.get(definition.challenge_id);const open=expanded===definition.challenge_id;return <article key={definition.challenge_id} className="rounded-3xl border border-white/10 bg-[#0e1b1b] p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.18em] text-[#687f79]">CHALLENGE {String(index+1).padStart(2,"0")}</p><h2 className="mt-2 text-2xl">{definition.title}</h2></div>{result?<Status value={result.status}/>:<span className="rounded-full bg-white/[.05] px-3 py-1 text-[10px] text-[#718982]">NOT RUN</span>}</div><Block label="TEST CONDITION" text={definition.question}/><Block label="WHY IT COULD FOOL A SIMPLE SYSTEM" text={definition.naive_failure_mode}/><Block label="EXPECTED INVARIANT" text={definition.expected_invariant}/><div className="mt-5 flex flex-wrap items-center gap-3"><button disabled={running!==null} onClick={()=>void run(definition.challenge_id)} className="rounded-full border border-[#70c5b1]/40 px-4 py-2 text-[10px] font-bold tracking-wider text-[#8bd9c7] disabled:opacity-40">{running===definition.challenge_id?"RUNNING…":"RUN CHALLENGE"}</button>{result&&<button onClick={()=>setExpanded(open?null:definition.challenge_id)} className="text-xs text-[#80958f]">{open?"Hide evidence":"Inspect actual evidence"}</button>}</div>{result&&<div className="mt-5 rounded-2xl border border-white/[.07] bg-black/15 p-4"><p className="text-[10px] font-bold tracking-wider text-[#73988f]">AEQUOR&apos;S ACTUAL PIPELINE RESPONSE</p><p className="mt-2 text-sm leading-6 text-[#a6b7b2]">{result.explanation}</p><div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(result.observed_evidence.invariant_checks).map(([k,v])=><div key={k} className="flex items-center justify-between gap-2 rounded-lg bg-white/[.04] p-2 text-[10px]"><span className="text-[#81938e]">{pretty(k)}</span><b className={v===true?"text-[#7bd4bd]":v===false?"text-[#e4937e]":"text-[#d2b36d]"}>{v===true?"PASS":v===false?"FAIL":"N/A"}</b></div>)}</div>{open&&<><p className="mt-5 text-[10px] font-bold tracking-wider text-[#73988f]">RECORDED EVIDENCE</p><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap rounded-xl bg-black/20 p-3 text-[10px] leading-5 text-[#91a49f]">{JSON.stringify(result.observed_evidence.observations,null,2)}</pre><p className="mt-3 text-[10px] text-[#687f79]">Runtime cycles: {result.runtime_cycle_ids.length?result.runtime_cycle_ids.join(", "):"Structural inspection — no cycle required"}</p></>}</div>}</article>})}</section>
  <section className="mt-5 rounded-3xl border border-[#d1a16f]/20 bg-[#1b1c17] p-6"><p className="text-[10px] font-bold tracking-[.18em] text-[#d1a16f]">INTERPRETATION BOUNDARY</p><p className="mt-3 max-w-4xl text-sm leading-7 text-[#a9aaa0]">PASS means the stated engineering invariant held in this deterministic synthetic run. FAIL means it did not. INCONCLUSIVE means the available observation could not establish the invariant. None of these labels measures clinical performance.</p></section>
 </div></main>
}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-[#0e1b1b] p-5"><p className="text-[9px] uppercase tracking-wider text-[#718780]">{label}</p><p className="mt-2 text-3xl font-light">{value}</p></div>}
function Status({value}:{value:Result["status"]}){const c=value==="PASS"?"border-[#68c6ad]/30 bg-[#68c6ad]/10 text-[#8edbc8]":value==="FAIL"?"border-[#de826d]/30 bg-[#de826d]/10 text-[#eda18f]":"border-[#d2af67]/30 bg-[#d2af67]/10 text-[#e2c78e]";return <span className={`rounded-full border px-3 py-1 text-[10px] font-bold ${c}`}>{value}</span>}
function Block({label,text}:{label:string;text:string}){return <div className="mt-4"><p className="text-[9px] font-bold tracking-wider text-[#667d76]">{label}</p><p className="mt-1 text-sm leading-6 text-[#a1b0ac]">{text}</p></div>}
function pretty(value:string){return value.replaceAll("_"," ")}
