"use client";
import { useCallback, useEffect, useState } from "react";
import { TopNav } from "./engineering-console";

const api=process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
type Params={r_zero_ohm:number;r_infinity_ohm:number;tau_seconds:number;beta:number};
type Spectrum={frequency_hz:number;resistance_ohm:number;reactance_ohm:number;magnitude_ohm:number;phase_deg:number};
type Inspector={title:string;provenance_label:string;disclosure:string;equation:Record<string,string>;scenario_ground_truth:Record<string,unknown>;arm_parameters:{arm:string;base:Params;effective:Params;modifier:Record<string,number>}[];parameter_evolution:{progression:number;left:Params;right:Params}[];model_prediction:Record<string,Spectrum[]>;latest_acquired_sweep:{simulated_time:string;left:Spectrum[];right:Spectrum[]}|null;fit_comparison:{parameter:string;arm:string;ground_truth_value:number;processor_estimate:number|null;difference:number|null;fit_available:boolean}[];virtual_sensors:{available:boolean;motion_condition:string|null;posture_condition:string|null;gravity_projection_m_s2:Record<string,number>|null;motion_level_rad_s:Record<string,number>|null;skin_temperature_c:Record<string,number>|null;contact_impedance_ohm:Record<string,number>|null;technical_quality:string|null;quality_score:number|null;technical_details:Record<string,unknown>|null};anti_leakage:{observed_path:string[];blocked_paths:string[];statement:string};noise_explanation:string[]};

export function DigitalTwinInspector(){
 const [d,setD]=useState<Inspector|null>(null); const load=useCallback(async()=>setD(await (await fetch(`${api}/api/v1/views/digital-twin`)).json()),[]);
 useEffect(()=>{const first=setTimeout(()=>void load(),0);const id=setInterval(()=>void load(),5000);return()=>{clearTimeout(first);clearInterval(id)}},[load]);
 if(!d)return <main className="min-h-screen bg-[#071310] p-8 text-white">Preparing Digital Twin Inspector…</main>;
 const g=d.scenario_ground_truth;
 return <main className="min-h-screen bg-[#071310] text-[#e7f0ec]">
  <TopNav active="Digital Twin"/><div className="mx-auto max-w-[1500px] px-5 py-7 sm:px-8">
   <header className="rounded-[2rem] border border-[#72b7a8]/20 bg-[#0d201c] p-6 sm:p-9"><p className="text-[11px] font-bold tracking-[.23em] text-[#72c6b3]">{d.provenance_label}</p><h1 className="mt-3 text-4xl font-light sm:text-6xl">{d.title}</h1><p className="mt-5 max-w-4xl text-sm leading-7 text-[#9cafaa]">{d.disclosure}</p></header>
   <section className="mt-5 grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><Card eyebrow="AUTHORITATIVE PHASE-2 MODEL" title="Cole model"><p className="overflow-x-auto rounded-2xl bg-black/20 p-5 font-mono text-lg text-[#9ee0cf] sm:text-2xl">{d.equation.cole}</p><p className="mt-3 font-mono text-sm">{d.equation.angular_frequency}</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{["r_zero","r_infinity","tau","beta"].map(k=><p key={k} className="rounded-xl bg-white/[.035] p-3 text-xs text-[#91a7a1]">{d.equation[k]}</p>)}</div></Card><Card eyebrow="GROUND TRUTH — NOT AN AEQUOR INFERENCE" title="Scenario progression"><div className="grid grid-cols-2 gap-3"><Metric label="Scenario" value={String(g.scenario_type).replaceAll("_"," ")}/><Metric label="Configured arm" value={String(g.affected_arm??"BILATERAL / NONE")}/><Metric label="Scenario start" value={g.start_simulated_time?new Date(String(g.start_simulated_time)).toLocaleString():"Not started"}/><Metric label="Elapsed simulated time" value={`${(Number(g.elapsed_simulated_time)/86400).toFixed(2)} days`}/></div><div className="mt-5 h-2 rounded bg-white/10"><div className="h-full rounded bg-[#d0ae6a]" style={{width:`${Number(g.synthetic_progression)*100}%`}}/></div><p className="mt-2 text-right text-xs text-[#d0ae6a]">{(Number(g.synthetic_progression)*100).toFixed(1)}% synthetic progression</p></Card></section>
   <section className="mt-5 grid gap-5 lg:grid-cols-2">{d.arm_parameters.map(a=><Card key={a.arm} eyebrow={`${a.arm} ARM`} title="Base → effective parameters"><div className="grid grid-cols-3 gap-2 text-xs"><b className="text-[#6f8882]">PARAMETER</b><b className="text-[#6f8882]">BASE</b><b className="text-[#6f8882]">EFFECTIVE</b>{paramRows(a.base,a.effective)}</div><div className="mt-5 grid grid-cols-2 gap-2">{Object.entries(a.modifier).map(([k,v])=><Metric key={k} label={k.replaceAll("_"," ")} value={scientific(v)}/>)}</div></Card>)}</section>
   <CardWrap><div className="mb-5"><p className="text-[10px] font-bold tracking-[.2em] text-[#6f9f94]">READ-ONLY DETERMINISTIC PREVIEW</p><h2 className="mt-2 text-2xl">Effective parameter evolution</h2></div><div className="grid gap-4 md:grid-cols-2">{([['R0','r_zero_ohm'],['R∞','r_infinity_ohm'],['τ','tau_seconds'],['β','beta']] as const).map(([label,key])=><MiniChart key={key} label={label} points={d.parameter_evolution} field={key}/>)}</div></CardWrap>
   <section className="mt-5 grid gap-5 xl:grid-cols-2"><Card eyebrow="MODEL PREDICTION" title="Noise-free Cole spectra"><SpectrumChart predicted={d.model_prediction} acquired={null}/><Legend/></Card><Card eyebrow="ACQUIRED SIMULATED NOISY SWEEP" title="Latest observation">{d.latest_acquired_sweep?<><SpectrumChart predicted={d.model_prediction} acquired={d.latest_acquired_sweep}/><Legend actual/></>:<Empty text="No acquired sweep yet. Run a qualified cycle in Aequor Lab."/>}<ul className="mt-4 space-y-2 text-xs text-[#849b95]">{d.noise_explanation.map(x=><li key={x}>• {x}</li>)}</ul></Card></section>
   <CardWrap><p className="text-[10px] font-bold tracking-[.2em] text-[#6f9f94]">HIDDEN VS ESTIMATED</p><h2 className="mt-2 text-2xl">Cole fit comparison</h2><p className="mt-2 text-sm text-[#8fa49f]">{d.anti_leakage.statement}</p>{d.fit_comparison.length?<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-[10px] uppercase text-[#718a84]"><tr><th>Arm</th><th>Parameter</th><th>Hidden effective</th><th>Processor estimate</th><th>Difference</th></tr></thead><tbody>{d.fit_comparison.map((x,i)=><tr key={`${x.arm}-${x.parameter}-${i}`} className="border-t border-white/[.06]"><td>{x.arm}</td><td>{x.parameter}</td><td>{scientific(x.ground_truth_value)}</td><td>{x.processor_estimate==null?"—":scientific(x.processor_estimate)}</td><td>{x.difference==null?"—":scientific(x.difference)}</td></tr>)}</tbody></table></div>:<Empty text="A qualified acquired sweep is required for a processor fit."/>}</CardWrap>
   <section className="mt-5 grid gap-5 xl:grid-cols-2"><Card eyebrow="SIMULATED SENSOR DATA" title="Virtual sensor inspector">{d.virtual_sensors.available?<><div className="grid grid-cols-2 gap-2"><Metric label="IMU condition" value={String(d.virtual_sensors.motion_condition)}/><Metric label="Posture condition" value={String(d.virtual_sensors.posture_condition)}/><Metric label="Technical quality" value={String(d.virtual_sensors.technical_quality)}/><Metric label="Quality score" value={fmt(d.virtual_sensors.quality_score)}/>{sensorMetrics(d.virtual_sensors)}</div><details className="mt-4 rounded-xl border border-white/10 p-4 text-xs text-[#8ca19c]"><summary className="cursor-pointer text-white">Expandable technical details</summary><pre className="mt-3 overflow-auto whitespace-pre-wrap">{JSON.stringify(d.virtual_sensors.technical_details,null,2)}</pre></details></>:<Empty text="No virtual sensor window acquired yet."/>}<div className="mt-5 flex flex-wrap items-center gap-2 text-[10px] text-[#91a7a1]"><span>Synthetic sensor conditions</span><b>→</b><span>Phase-4 Technical Quality Engine</span><b>→</b><span>QUALIFIED / REJECTED</span></div></Card><Card eyebrow="ANTI-LEAKAGE BOUNDARY" title="What Aequor can actually see"><div className="space-y-2">{d.anti_leakage.observed_path.map((x,i)=><div key={x} className="text-center"><div className="rounded-xl border border-[#6fc3b0]/20 bg-[#6fc3b0]/[.06] p-2 text-sm">{x}</div>{i<d.anti_leakage.observed_path.length-1&&<span className="text-[#66857d]">↓</span>}</div>)}</div><div className="mt-5 space-y-2">{d.anti_leakage.blocked_paths.map(x=><p key={x} className="rounded-xl border border-[#d48b76]/20 bg-[#d48b76]/[.06] p-3 text-xs text-[#d9a18f]">{x}</p>)}</div></Card></section>
  </div>
 </main>
}

function Card({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="rounded-3xl border border-white/10 bg-[#0d1e1b] p-6"><p className="text-[10px] font-bold tracking-[.18em] text-[#739d93]">{eyebrow}</p><h2 className="mt-2 mb-5 text-2xl font-light">{title}</h2>{children}</section>}
function CardWrap({children}:{children:React.ReactNode}){return <section className="mt-5 rounded-3xl border border-white/10 bg-[#0d1e1b] p-6">{children}</section>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white/[.04] p-3"><p className="text-[9px] uppercase tracking-wider text-[#718982]">{label}</p><p className="mt-1 text-sm break-words">{value}</p></div>}
function paramRows(base:Params,effective:Params){return (Object.keys(base) as (keyof Params)[]).flatMap(k=>[<span key={`${k}-l`} className="border-t border-white/[.05] py-2 text-[#89a09a]">{k.replaceAll("_"," ")}</span>,<span key={`${k}-b`} className="border-t border-white/[.05] py-2">{scientific(base[k])}</span>,<span key={`${k}-e`} className="border-t border-white/[.05] py-2 text-[#8bd4c2]">{scientific(effective[k])}</span>])}
function MiniChart({label,points,field}:{label:string;points:Inspector["parameter_evolution"];field:keyof Params}){const vals=points.flatMap(p=>[p.left[field],p.right[field]]);const min=Math.min(...vals),max=Math.max(...vals);const path=(side:"left"|"right")=>points.map((p,i)=>`${8+i*23},${52-(max===min?0.5:(p[side][field]-min)/(max-min))*38}`).join(" ");return <div className="rounded-2xl bg-black/15 p-4"><p className="text-xs text-[#91aaa3]">{label}</p><svg viewBox="0 0 108 60" className="mt-2 h-32 w-full" role="img" aria-label={`${label} by scenario progression`}><polyline points={path("left")} fill="none" stroke="#6fd1bb" strokeWidth="2"/><polyline points={path("right")} fill="none" stroke="#d0ae6a" strokeWidth="2"/></svg><p className="text-[9px] text-[#68827b]">0% · 25% · 50% · 75% · 100%</p></div>}
function SpectrumChart({predicted,acquired}:{predicted:Record<string,Spectrum[]>;acquired:Inspector["latest_acquired_sweep"]}){const series=[predicted.LEFT,predicted.RIGHT,...(acquired?[acquired.left,acquired.right]:[])];const vals=series.flatMap(x=>x.map(p=>p.magnitude_ohm));const min=Math.min(...vals),max=Math.max(...vals);const path=(xs:Spectrum[])=>xs.map((p,i)=>`${7+i*18.5},${63-((p.magnitude_ohm-min)/(max-min||1))*48}`).join(" ");return <svg viewBox="0 0 106 70" className="h-52 w-full" role="img" aria-label="Cole magnitude spectrum"><polyline points={path(predicted.LEFT)} fill="none" stroke="#6fd1bb" strokeWidth="1.8"/><polyline points={path(predicted.RIGHT)} fill="none" stroke="#d0ae6a" strokeWidth="1.8"/>{acquired&&<><polyline points={path(acquired.left)} fill="none" stroke="#6fd1bb" strokeDasharray="2 2"/><polyline points={path(acquired.right)} fill="none" stroke="#d0ae6a" strokeDasharray="2 2"/></>}<text x="7" y="69" fill="#6f8982" fontSize="3">5</text><text x="96" y="69" fill="#6f8982" fontSize="3">200 kHz</text></svg>}
function Legend({actual=false}:{actual?:boolean}){return <p className="text-[10px] text-[#718982]"><span className="text-[#6fd1bb]">— LEFT</span> · <span className="text-[#d0ae6a]">— RIGHT</span>{actual&&" · dashed = acquired observation"}</p>}
function sensorMetrics(s:Inspector["virtual_sensors"]){const items:[string,Record<string,number>|null,string][]=[["Gravity projection",s.gravity_projection_m_s2,"m/s²"],["Motion level",s.motion_level_rad_s,"rad/s"],["Skin temperature",s.skin_temperature_c,"°C"],["Contact impedance",s.contact_impedance_ohm,"Ω"]];return items.flatMap(([label,v,u])=>(["LEFT","RIGHT"] as const).map(side=><Metric key={`${label}-${side}`} label={`${side} ${label}`} value={v?`${fmt(v[side])} ${u}`:"—"}/>))}
function Empty({text}:{text:string}){return <p className="mt-5 rounded-xl bg-white/[.03] p-5 text-sm text-[#758d87]">{text}</p>}
function scientific(v:number){return Math.abs(v)>0&&Math.abs(v)<.001?v.toExponential(3):v.toFixed(4)} function fmt(v:number|null){return v==null?"—":v.toFixed(2)}
