"use client";
import { useCallback, useEffect, useState } from "react";
import { TopNav } from "./engineering-console";

const api=process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:8000";
type Privacy={title:string;prototype_mode:string;disclosure:string;data_sources:{classification:string;items:string[];location:string}[];processing_stages:{stage:string;execution_location:string}[];data_flow:{intelligence_path:string[];cloud_inference_branch:null;application_topology:string[]};storage_locations:{data:string;location:string;lifetime:string;used_by:string}[];network_dependencies:Record<string,unknown>;external_services:string[];model_execution:Record<string,unknown>;retention_behavior:Record<string,string[]>;sensitive_data_boundary:{engineering_truth_allowed_in:string[];engineering_truth_forbidden_from:string[];statement:string};audience_boundaries:{audience:string;scope:string}[];simulated_vs_real:Record<string,string[]>;not_yet_implemented:string[];planned_hardware_deployment:{status:string;components:string[];current_execution:string};limitations:string[]};
export function PrivacyInspector(){
 const [d,setD]=useState<Privacy|null>(null);const [error,setError]=useState(false);const load=useCallback(async()=>{try{const response=await fetch(`${api}/api/v1/views/privacy`);if(!response.ok)throw new Error();setD(await response.json());setError(false)}catch{setError(true)}},[]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 if(error)return <main className="min-h-screen bg-[#f3f5f1] p-8 text-[#17312d]"><b>BACKEND UNAVAILABLE</b><p className="mt-3 text-sm">Privacy architecture data could not be refreshed.</p></main>;
 if(!d)return <main className="min-h-screen bg-[#f3f5f1] p-8 text-[#17312d]">Preparing privacy inspector…</main>;
 return <main className="min-h-screen bg-[#edf2ee] text-[#17312d]"><TopNav active="Privacy"/><div className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8">
  <header className="rounded-[2rem] border border-[#b8cac2] bg-[#f8faf7] p-7 sm:p-10"><p className="text-[11px] font-bold tracking-[.22em] text-[#387566]">CURRENT IMPLEMENTATION · {d.prototype_mode}</p><h1 className="mt-3 text-4xl font-light sm:text-6xl">{d.title}</h1><p className="mt-5 max-w-4xl text-sm leading-7 text-[#58706a]">{d.disclosure}</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><Truth label="Cloud inference required" value={String(d.network_dependencies.cloud_inference_required?"YES":"NO")}/><Truth label="External model API" value={String(d.network_dependencies.external_model_api_required?"REQUIRED":"NONE")}/><Truth label="Core inference" value="LOCAL"/></div></header>
  <section className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card title="Exact intelligence data flow" eyebrow="NO CLOUD INFERENCE BRANCH"><Flow items={d.data_flow.intelligence_path}/><p className="mt-5 rounded-xl bg-[#e7efea] p-4 text-xs text-[#527069]">Cloud inference branch: <b>NONE</b>. Internet is not required for core inference; locally installed dependencies are required.</p></Card><Card title="Current application topology" eyebrow="LOCAL TRANSPORT"><Flow items={d.data_flow.application_topology}/><div className="mt-5 grid grid-cols-2 gap-2">{Object.entries(d.network_dependencies).map(([k,v])=><Line key={k} label={k} value={typeof v==="boolean"?(v?"YES":"NO"):String(v)}/>)}</div></Card></section>
  <section className="mt-5 grid gap-5 lg:grid-cols-3">{d.data_sources.map((group,i)=><Card key={group.classification} title={group.classification} eyebrow={i===2?"ENGINEERING ONLY":"LOCAL DATA"}><ul className="space-y-2 text-sm text-[#4f6963]">{group.items.map(x=><li key={x}>• {x}</li>)}</ul><p className="mt-5 border-t border-[#d3dfda] pt-3 text-xs text-[#6f817c]">Location: {group.location}</p></Card>)}</section>
  <section className="mt-5 rounded-3xl border border-[#bfd0c9] bg-[#f8faf7] p-6"><p className="text-[10px] font-bold tracking-[.18em] text-[#528074]">DATA RETENTION — CURRENT PROTOTYPE</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-[10px] uppercase text-[#687d77]"><tr><th>Data</th><th>Location</th><th>Lifetime</th><th>Used by</th></tr></thead><tbody>{d.storage_locations.map(x=><tr key={x.data} className="border-t border-[#d8e1dd]"><td>{x.data}</td><td>{x.location}</td><td>{x.lifetime}</td><td>{x.used_by}</td></tr>)}</tbody></table></div><div className="mt-6 grid gap-3 md:grid-cols-3">{Object.entries(d.retention_behavior).map(([k,items])=><div key={k} className="rounded-xl bg-[#eaf0ec] p-4"><h3 className="text-[10px] font-bold uppercase tracking-wider text-[#52736b]">{k.replaceAll("_"," ")}</h3><ul className="mt-3 space-y-2 text-xs text-[#60756f]">{items.map(x=><li key={x}>• {x}</li>)}</ul></div>)}</div></section>
  <section className="mt-5 grid gap-5 xl:grid-cols-2"><Card title="Local model execution" eyebrow="ACTUAL LOADED ARTIFACT"><div className="grid grid-cols-2 gap-2">{Object.entries(d.model_execution).map(([k,v])=><Line key={k} label={k} value={String(v??"—")}/>)}</div><p className="mt-5 rounded-xl border border-[#c8d8d1] p-4 text-sm leading-6 text-[#506b64]">The trained artifact is loaded locally. If absent or hash verification fails, Aequor reports <b>ML_UNAVAILABLE</b> rather than generating a fallback score.</p></Card><Card title="Ground-truth privacy boundary" eyebrow="AUDIENCE MINIMIZATION"><p className="text-sm text-[#506b64]">{d.sensitive_data_boundary.statement}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Boundary title="Allowed engineering views" items={d.sensitive_data_boundary.engineering_truth_allowed_in}/><Boundary title="Forbidden intelligence/product inputs" items={d.sensitive_data_boundary.engineering_truth_forbidden_from}/></div></Card></section>
  <section className="mt-5 grid gap-3 md:grid-cols-3">{d.audience_boundaries.map(x=><div key={x.audience} className="rounded-2xl border border-[#c4d3cd] bg-[#f8faf7] p-5"><p className="text-[10px] font-bold tracking-wider text-[#47796e]">{x.audience}</p><p className="mt-3 text-sm leading-6 text-[#596f69]">{x.scope}</p></div>)}</section>
  <section className="mt-5 grid gap-5 xl:grid-cols-2"><div className="rounded-3xl border border-[#d5b8ad] bg-[#fff8f4] p-6"><p className="text-[10px] font-bold tracking-[.18em] text-[#9a5f4d]">NOT YET IMPLEMENTED</p><h2 className="mt-2 text-2xl">No implied production controls</h2><ul className="mt-5 grid gap-2 sm:grid-cols-2">{d.not_yet_implemented.map(x=><li key={x} className="rounded-xl bg-[#f8eae4] p-3 text-xs text-[#75584e]">{x}</li>)}</ul></div><div className="rounded-3xl border border-[#bfc9db] bg-[#f5f7fc] p-6"><p className="text-[10px] font-bold tracking-[.18em] text-[#5c7098]">{d.planned_hardware_deployment.status}</p><h2 className="mt-2 text-2xl">Planned hardware deployment</h2><p className="mt-3 text-sm text-[#5f6980]">Current: {d.planned_hardware_deployment.current_execution}</p><ul className="mt-5 grid gap-2 sm:grid-cols-2">{d.planned_hardware_deployment.components.map(x=><li key={x} className="rounded-xl bg-[#e9edf7] p-3 text-xs text-[#59667e]">{x}</li>)}</ul></div></section>
  <section className="mt-5 rounded-3xl border border-[#c2d0ca] bg-[#f8faf7] p-6"><p className="text-[10px] font-bold tracking-[.18em] text-[#52766d]">SCIENTIFIC & SECURITY LIMITATIONS</p><ul className="mt-4 grid gap-2 md:grid-cols-2">{d.limitations.map(x=><li key={x} className="text-sm text-[#5d736d]">• {x}</li>)}</ul></section>
 </div><style jsx global>{`table th,table td{padding:.7rem .55rem;vertical-align:top}`}</style></main>
}
function Card({title,eyebrow,children}:{title:string;eyebrow:string;children:React.ReactNode}){return <section className="rounded-3xl border border-[#c4d3cd] bg-[#f8faf7] p-6"><p className="text-[10px] font-bold tracking-[.18em] text-[#527b71]">{eyebrow}</p><h2 className="mt-2 mb-5 text-2xl font-light">{title}</h2>{children}</section>}
function Truth({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-[#e4eee9] p-4"><p className="text-[9px] uppercase text-[#657b75]">{label}</p><p className="mt-1 text-xl font-semibold text-[#277060]">{value}</p></div>}
function Flow({items}:{items:string[]}){return <div className="space-y-1">{items.map((x,i)=><div key={x} className="text-center"><div className="rounded-xl border border-[#c5d7d0] bg-[#edf3ef] p-2 text-sm">{x}</div>{i<items.length-1&&<span className="text-[#719188]">↓</span>}</div>)}</div>}
function Line({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#edf2ef] p-3"><p className="text-[9px] uppercase text-[#6b807a]">{label.replaceAll("_"," ")}</p><p className="mt-1 break-words text-xs">{value}</p></div>}
function Boundary({title,items}:{title:string;items:string[]}){return <div className="rounded-xl bg-[#eaf1ed] p-4"><h3 className="text-xs font-semibold">{title}</h3><ul className="mt-3 space-y-2 text-xs text-[#5c746d]">{items.map(x=><li key={x}>• {x}</li>)}</ul></div>}
